import type { Metadata } from 'next'
import './globals.css'
import { Inter as FontSans } from 'next/font/google'

import { cn } from '@/lib/utils'
import Image from 'next/image'
import { Button } from '@/components/ui/button'
import { Separator } from '@/components/ui/separator'
import { Toaster } from '@/components/ui/sonner'

export const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body
        className={cn(
          'min-h-screen bg-background font-sans antialiased',
          fontSans.variable,
        )}
      >
        <header>
          <div className='container mx-auto flex justify-between py-6'>
            <Image
              src='/logo.svg'
              alt='Image Uploader logo'
              width={120}
              height={26}
            />
            <Button variant='outline' size='icon'>
              <Image
                src='/moon-fill.svg'
                alt='Dark theme'
                width={24}
                height={24}
              />
            </Button>
          </div>
          <Separator />
        </header>

        <main>{children}</main>
        <Toaster position='top-right' closeButton />
      </body>
    </html>
  )
}
